### ISSUE TITLE
Compatibility with Spaces

### ISSUE THREAD

**Issue by jeff-h** [insidegui/GRGlassWindow#3]
Hi, this looks great, but unfortunately doesn't work well with OS X Spaces. Ordinary apps can be dragged between Spaces by dragging the window to the side of the screen. After a short delay it will change spaces. The window move you've implemented doesn't do this for me. Do you think there might be a workaround?

**Comment by insidegui** [comment]
Works fine here...

**Comment by insidegui** [comment]
Sorry, I think I misunderstood your issue, when trying to drag It to the side to change spaces It doesn't work, I'll see if I can get It working.

**Comment by jeff-h** [comment]
Yes, that's correct. Would be awesome if you could get it working—it's a beautiful window UI you've made.
