### ISSUE TITLE
Titlebar issue

### ISSUE THREAD

**Issue by egorzhdan** [insidegui/GRGlassWindow#4]
Piece of black background is shown at the top left corner of the window.

**Comment by egorzhdan** [comment]
http://postimg.org/image/ny46igpvj/

**Comment by insidegui** [comment]
I am unable to reproduce this issue. What version of OSX are you running? Are there any specific steps which make the bug appear?

**Comment by egorzhdan** [comment]
I'm using 10.8.5. I just run the app and got it.

**Comment by insidegui** [comment]
Sorry, I don't want to support 10.8, if you think It's important, feel free to fix It and send me a pull request.
