### ISSUE TITLE
Hides NSToolbar

### ISSUE THREAD

**Issue by ghost** [insidegui/GRGlassWindow#5]
GRGlassWindow with an NSToolbar results in a hidden and therefore unusable NSToolbar.

**Comment by insidegui** [comment]
I'm sorry, It's practically impossible to make NSToolbar work with this implementation, you'd have to delve into some really nasty private APIs to work around the problem, I think you'll be better of creating your own "toolbar view" and adding It to the titlebar =\

**Comment by ghost** [comment]
I thought it might be impractical. Still, a very good looking window :)
